### ISSUE TITLE
使用nginx转发请求socket.io返回404：Cannot GET /socket.io/

### ISSUE THREAD

**Issue by Greking** [jumpserver/luna#14]
请求链接：http://192.168.2.88/socket.io/?EIO=3&transport=polling&t=M34vXDF
直接请求 http://127.0.0.1:4200/socket.io/?EIO=3&transport=polling&t=M34vXDF
也是一样

有详细一点的教程吗？

**Comment by kaka1992** [comment]
有解决这个问题么？
