### ISSUE TITLE
web连接服务器后卡死

### ISSUE THREAD

**Issue by topicgit** [jumpserver/luna#15]
jms版本： Version 0.5.0-2 GPLv2
luna版本：0.5-alpha-2

登陆之后卡死，无法操作任何命令，表情是 0.0  ；录像回放是没问题的，请问应该如何来排查，
coco也没看到有日志报错，请帮忙看看，非常感谢

现象如下图：
![image](https://user-images.githubusercontent.com/11975460/34606609-0918da46-f24b-11e7-829b-a37f119f8f05.png)

  
  @liuzheng

**Comment by yamin-zou** [comment]
我连luna 都打不开 404

**Comment by liuzheng** [comment]
看guide啊，然后改问题应该已经fix了，如仍然有疑问，请在jumpserver里提issue
