### ISSUE TITLE
Luna 显示的资产列表，和资产列表、资产授权列表不一致

### ISSUE THREAD

**Issue by dbarobin** [jumpserver/luna#155]
> 备注：资产列表树，有过多次改名、重组。

Luna 显示的资产列表有 23 个，资产管理--->资产列表、权限管理--->资产授权列表，都是  20 个。

也就是说 Luna 多了 3 个孤立的节点。研究了下数据库表，没有找到怎么样删除 Luna 的这 3 个孤立节点。

按照这个文档部署，Jumpserver、Luna 应该都是最新版。

* https://jumpserver.readthedocs.io/zh/master/setup_by_ubuntu18.html

**Comment by orangemio** [comment]
麻烦提供一下截图

**Comment by dbarobin** [comment]
什么都没做，自动修复了
