### ISSUE TITLE
docker镜像 luna v0.4.0-beta1的使用问题

### ISSUE THREAD

**Issue by huoniu** [jumpserver/luna#20]
进入后上传、下载、语言等选项不可以使用，help中有输入授权码功能，是前面那些功能都是收费的吗？

**Comment by liuzheng** [comment]
为什么还有0.4？请使用release，<https://github.com/jumpserver/jumpserver/wiki/v0.5.0-%E5%9F%BA%E4%BA%8E-CentOS7#%E5%9B%9B-%E5%AE%89%E8%A3%85-web-terminal-%E5%89%8D%E7%AB%AF-luna>， 那几块功能没做。。。表示我们不对功能进行收费，只对服务进行收费，但是现在功能都没做好，没脸收服务费。。。

**Comment by huoniu** [comment]
docker的官方hub上最新的还是0.4.0，偷懒就直接pull下来用了。。。
祝你们早日收到服务费。。。。。

**Comment by liuzheng** [comment]
呵呵，先整好功能吧，不好高骛远
