### ISSUE TITLE
luna 0.5-alpha-1版本怎么用啊

### ISSUE THREAD

**Issue by qianghong000** [jumpserver/luna#21]

**Comment by qianghong000** [comment]
1

**Comment by yamin-zou** [comment]
同问啊，用下面这个 去build一直报错啊，用这个线程的 也不行啊。
$ cd /opt
$ git clone https://github.com/jumpserver/luna.git
$ cd luna && npm install && npm run-script build

**Comment by liuzheng** [comment]
如果不是开发，请勿使用npm，参考<https://github.com/jumpserver/jumpserver/wiki/v0.5.0-%E5%9F%BA%E4%BA%8E-CentOS7#%E5%9B%9B-%E5%AE%89%E8%A3%85-web-terminal-%E5%89%8D%E7%AB%AF-luna>   进行安装
