### ISSUE TITLE
luna点击左侧hostname连接无反应

### ISSUE THREAD

**Issue by qianghong000** [jumpserver/luna#23]
下载了好几个包都试过了，页面上 luna点击左侧hostname连接无反应

**Comment by qianghong000** [comment]
https://github.com/jumpserver/jumpserver/issues/913  我用这位老哥的方式，自己buil的，就可以用了，请问这样和直接下载最新包是一样得吗？
cd /opt
$ git clone https://github.com/jumpserver/luna.git
$ cd luna && npm install && npm run-script build

**Comment by liuzheng** [comment]
这个应该已经修复了，请尝试使用1.0.0
