### ISSUE TITLE
luna web terminal的字体显示可以调整吗

### ISSUE THREAD

**Issue by ChuckPerry** [jumpserver/luna#27]
您好，luna的字体显示可以调整吗，或者后台是在哪里可以调整字体的？

**Comment by ibuler** [comment]
暂时通过修改代码来调整吧：

$ vim index.html
![image](https://user-images.githubusercontent.com/17382885/38068307-15eb6a02-3343-11e8-8fef-4807f5c82e67.png)

**Comment by ChuckPerry** [comment]
OK，收到。非常感谢

**Comment by hubeixulu** [comment]
@ChuckPerry Hi 你这个终端字体大小改成功了吗，我试了好多方法都没办法修改成功，还是那么小

**Comment by ChuckPerry** [comment]
> @ChuckPerry Hi 你这个终端字体大小改成功了吗，我试了好多方法都没办法修改成功，还是那么小

我是按照ibuler回复的方法做的，改了就好了
