### ISSUE TITLE
关于服务器连接超时时间问题

### ISSUE THREAD

**Issue by bindons** [jumpserver/luna#38]
请问超时时间可以调整吗，目前是10s超时，但有些场景下可能10s不够，请问在哪里可以修改超时时间呢？

**Comment by paulcst** [comment]
/opt/coco/coco/proxy.py中将TIMEOUT这个全局对象的值改一下。默认TIMEOUT = 10

**Comment by bindons** [comment]
@paulcst 好的，我试一下，感谢。
