### ISSUE TITLE
无法打包

### ISSUE THREAD

**Issue by noshake** [jumpserver/luna#47]
ERROR in : Cannot determine the module for class FileDropDirective in D:/work/luna/node_modules/ng2-f                                                                                           ile-upload/file-upload/file-drop.directive.d.ts! Add FileDropDirective to the NgModule to fix it.
Cannot determine the module for class FileSelectDirective in D:/work/luna/node_modules/ng2-file-uploa                                                                                           d/file-upload/file-select.directive.d.ts! Add FileSelectDirective to the NgModule to fix it.

**Comment by bypdhu** [comment]
@noshake 问题现在解决了吗？我也有同样的问题

**Comment by ibuler** [comment]
node 10.0版本测试没有问题

**Comment by zhusipu** [comment]
解决了。。。我打包用的 npm  或者 yarn 都会报这个错误，要用ng命令去运行。。。。

**Comment by zhusipu** [comment]
@noshake @bypdhu  现在告诉你们还来得及吗？
`cnpm install -g @angular/cli`
