### ISSUE TITLE
terminal能看到正常登录，但是不能输入任何字符

### ISSUE THREAD

**Issue by Jason20015** [jumpserver/luna#6]
![terminal](https://user-images.githubusercontent.com/12149060/27373135-a9f1cdcc-5699-11e7-81e2-82bc77befc27.png)
图中能看到可以正常登录到目标主机但是输入任何字符都没有显示，各种浏览器都试了不行
部署方式:非docker
通过查看浏览器请求和debug日志，实际上输入的字符已经post到后端
![luna-debug-log](https://user-images.githubusercontent.com/12149060/27373222-123dec3a-569a-11e7-9a5a-78e4d1223d4e.png)

**Comment by ibuler** [comment]
python版本？ python3 还是 2

**Comment by Jason20015** [comment]
已经解决了．尝试了python2.7 python3.6 python3.5 发现只有python3.5可以
