### ISSUE TITLE
coco，资产组没用户

### ISSUE THREAD

**Issue by yokiy0828** [jumpserver/luna#8]
选择资产组没用户，登录不了。
<img width="595" alt="coco" src="https://user-images.githubusercontent.com/25323406/28490288-10557992-6f09-11e7-8fc1-bf4477cea7ee.png">

**Comment by hellorocky** [comment]
没有系统用户, 提示你了

**Comment by yokiy0828** [comment]
但是我是有系统用户的  按p能打印，在组里面就显示没有。
