### ISSUE TITLE
App auth failed, Access key error or need admin active it

### ISSUE THREAD

**Issue by gengkeye** [jumpserver/luna#9]
I'v already accept it in my jumpserver terminal panel. And I restarted both of jumpserver and luna. But it still
displayed: 
`(py3) [seven@localhost luna]$ python run_server.py 
Using access key b2313335-8daa-4fa1-99b5-6386bbcc8601:***
App auth failed, Access key error or need admin active it
App auth failed, Access key error or need admin active it
`

**Comment by ibuler** [comment]
这是使用问题，需要在jumpserver - 应用程序 接受注册

**Comment by gengkeye** [comment]
我已经接受注册了，但是还是报这个错误。

**Comment by hellorocky** [comment]
把 `luna/keys/.access_kay`删除后再激活试试~

**Comment by gengkeye** [comment]
删除luna/keys/.access_kay也不行，这个文件是注册的时候自动生成的。
删除后再启动服务是会报错：
`
(luna) [seven@node2-jmp40-release luna]$ python run_server.py 
ERROR:root:Load access key failed
ERROR:root:Terminal luna exist already, register failed
Register terminal failed, may be have been exist, you should look for the terminal access key, set in config, or put it in access key store
(luna) [seven@node2-jmp40-release luna]$ 
`

**Comment by hellorocky** [comment]
修改一下config中的那个app名字

**Comment by gengkeye** [comment]
不行

**Comment by liuzheng** [comment]
暂时关闭，敬请期待下一版本
